### ISSUE TITLE
How to dynamic import a css with useDark?

### ISSUE THREAD

**Issue by rromanv** [vueuse/vueuse#308]
If we are not using tailwind, is there a way to dynamic import (and unload of course) a dark/light css theme?

I'm thinking in implement this with primevue

**Comment by antfu** [comment]
`useDark` only responsible for togglin your DOM attributes while the styling should be handled by your framework or yourself. For example to have the Tailwind-liked style:

```css
html {
  background: white;
} 

html.dark {
  background: black;
  color: white;
}
```
